version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: attend-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: attend
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - attend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attend-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/attend?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      CORS_ORIGIN: http://localhost:3000
      SOCKET_CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - attend-network
    volumes:
      - ./backend/qrcodes:/app/qrcodes

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: attend-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - attend-network

volumes:
  mongodb_data:

networks:
  attend-network:
    driver: bridge
