@echo off
SETLOCAL EnableDelayedExpansion

echo ======================================================
echo      Starting Attend App (Frontend and Backend)
echo ======================================================
echo.

REM Get the computer's IP address (more reliable method)
FOR /F "tokens=4 delims= " %%i IN ('route print ^| find "0.0.0.0" ^| find /v "127.0.0.1"') DO (
    IF "!IP!"=="" SET IP=%%i
)

REM Fallback method if the above fails
IF "!IP!"=="" (
    FOR /F "tokens=2 delims=:" %%a IN ('ipconfig ^| findstr /C:"IPv4 Address"') DO (
        SET IP=%%a
        SET IP=!IP:~1!
        GOTO :found_ip
    )
)
:found_ip

REM Check if we found an IP
IF "!IP!"=="" (
    echo ERROR: Could not detect your computer's IP address.
    echo Please enter your IP address manually:
    set /p IP=Enter your computer's IP address: 
)

SET HOST=0.0.0.0
SET PORT=3000
SET HTTPS=false
SET REACT_APP_API_URL=http://%IP%:5000/api
SET REACT_APP_SERVER_IP=%IP%
SET REACT_APP_FRONTEND_PORT=3000
SET REACT_APP_BACKEND_PORT=5000

echo IP Address detected: %IP%
echo.
echo Mobile devices should connect using:
echo Frontend: http://%IP%:3000
echo Backend API: http://%IP%:5000/api
echo.
echo Make sure that:
echo 1. Your phone and computer are on the same WiFi network
echo 2. Windows Firewall is not blocking connections
echo 3. Both frontend and backend will be started automatically
echo.
echo Press Ctrl+C in the respective windows to stop the servers
echo ======================================================
echo.

REM Update frontend network config file
set CONFIG_FILE=frontend\src\config\network.config.js
echo // Auto-generated by start-all.bat > frontend\temp.js
echo const defaultConfig = { >> frontend\temp.js
echo   serverIP: "%IP%", >> frontend\temp.js
echo   frontendPort: 3000, >> frontend\temp.js
echo   backendPort: 5000, >> frontend\temp.js
echo   useHttps: false >> frontend\temp.js
echo }; >> frontend\temp.js
echo export default defaultConfig; >> frontend\temp.js

copy /Y frontend\temp.js %CONFIG_FILE% > nul
echo Updated frontend network configuration with IP: %IP%
echo.

REM Start the backend in a new window
echo Starting backend server...
start "Attend Backend" cmd /c "cd backend && set PORT=5000 && set HOST=0.0.0.0 && node server.js"

REM Small delay to let backend start first
timeout /t 5 /nobreak > nul

REM Start the frontend in a new window
echo Starting frontend server...
start "Attend Frontend" cmd /c "cd frontend && npm start"

echo.
echo Both servers started successfully!
echo Frontend server is running at http://%IP%:3000
echo Backend server is running at http://%IP%:5000
echo.
echo To stop the servers, close their respective command windows or press Ctrl+C in each window.
echo ======================================================
