@echo off
rem startall-network.bat - Batch script to start both frontend and backend of Attend System for network access
rem Author: GitHub Copilot
rem Created: June 4, 2025

echo Starting Attend System for network access...
echo ------------------------------

rem Define paths
set FRONTEND_PATH=%~dp0frontend
set BACKEND_PATH=%~dp0backend

rem Check if paths exist
if not exist "%FRONTEND_PATH%" (
    echo ERROR: Frontend folder not found at %FRONTEND_PATH%
    exit /b 1
)

if not exist "%BACKEND_PATH%" (
    echo ERROR: Backend folder not found at %BACKEND_PATH%
    exit /b 1
)

rem Check npm installation
where npm >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo ERROR: npm is not installed or not in PATH
    echo Please install Node.js and npm before running this script.
    exit /b 1
)

rem Get local IP address - improved method that works for different language versions of Windows
setlocal EnableDelayedExpansion
set LOCAL_IP=

rem Try multiple approaches to get IP address for more reliable detection
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /r /c:"IPv4 Address"') do (
    set LOCAL_IP=%%a
    set LOCAL_IP=!LOCAL_IP:~1!
    goto :found_ip
)

rem Fallback approach
if "%LOCAL_IP%"=="" (
    for /f "tokens=2 delims=[]" %%a in ('ping -4 -n 1 %computername% ^| findstr /r /c:"\["') do (
        set LOCAL_IP=%%a
        goto :found_ip
    )
)

rem Another fallback approach
if "%LOCAL_IP%"=="" (
    for /f "tokens=2 delims=:" %%a in ('ipconfig ^| find "192.168." ^| find /v "Subnet"') do (
        set LOCAL_IP=%%a
        set LOCAL_IP=!LOCAL_IP:~1!
        goto :found_ip
    )
)

:found_ip
if "%LOCAL_IP%"=="" (
    echo WARNING: Could not automatically detect IP address. Using localhost.
    set LOCAL_IP=localhost
)

echo Your local IP address is: %LOCAL_IP%

rem Generate dynamic network config file
echo // Auto-generated by startall-network.bat > "%FRONTEND_PATH%\src\config\network.config.js"
echo // Last updated: %DATE% %TIME% >> "%FRONTEND_PATH%\src\config\network.config.js"
echo const defaultConfig = { >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   serverIP: "auto", >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   frontendPort: 3000, >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   backendPort: 5000, >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   qrServicePort: 5005, >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   useHttps: false >> "%FRONTEND_PATH%\src\config\network.config.js"
echo }; >> "%FRONTEND_PATH%\src\config\network.config.js"
echo export default defaultConfig; >> "%FRONTEND_PATH%\src\config\network.config.js"

echo Network configuration file updated with auto IP detection.

echo Starting backend server for network access...
start "Attend Backend Network" cmd /k "cd /d "%BACKEND_PATH%" && set HOST=0.0.0.0 && npm run dev"

rem Wait a moment to let backend initialize
echo Waiting for backend to initialize...
timeout /t 5 /nobreak >nul

echo Starting frontend server for network access...
start "Attend Frontend Network" cmd /k "cd /d "%FRONTEND_PATH%" && npm run start-network"

echo.
echo Attend System startup complete for network access!
echo Backend URL: http://%LOCAL_IP%:5000
echo Frontend URL: http://%LOCAL_IP%:3000
echo.
echo Other devices on your network can access the system using the above URLs
echo Press Ctrl+C in each terminal window to stop the servers
