@echo off
rem startall.bat - Batch script to start both frontend and backend of Attend System
rem Author: GitHub Copilot
rem Created: June 4, 2025

echo Starting Attend System...
echo ------------------------------

rem Define paths
set FRONTEND_PATH=%~dp0frontend
set BACKEND_PATH=%~dp0backend

rem Check if paths exist
if not exist "%FRONTEND_PATH%" (
    echo ERROR: Frontend folder not found at %FRONTEND_PATH%
    exit /b 1
)

if not exist "%BACKEND_PATH%" (
    echo ERROR: Backend folder not found at %BACKEND_PATH%
    exit /b 1
)

rem Check npm installation
where npm >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo ERROR: npm is not installed or not in PATH
    echo Please install Node.js and npm before running this script.
    exit /b 1
)

rem Generate dynamic network config file for auto IP detection
echo // Auto-generated by startall.bat > "%FRONTEND_PATH%\src\config\network.config.js"
echo // Last updated: %DATE% %TIME% >> "%FRONTEND_PATH%\src\config\network.config.js"
echo const defaultConfig = { >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   serverIP: "auto", >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   frontendPort: 3000, >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   backendPort: 5000, >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   qrServicePort: 5005, >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   useHttps: false >> "%FRONTEND_PATH%\src\config\network.config.js"
echo }; >> "%FRONTEND_PATH%\src\config\network.config.js"
echo export default defaultConfig; >> "%FRONTEND_PATH%\src\config\network.config.js"

echo Network configuration file updated with auto IP detection.

echo Starting backend server...
start "Attend Backend" cmd /k "cd /d "%BACKEND_PATH%" && npm start"

rem Wait a moment to let backend initialize
echo Waiting for backend to initialize...
timeout /t 5 /nobreak >nul

echo Starting frontend server...
start "Attend Frontend" cmd /k "cd /d "%FRONTEND_PATH%" && npm start"

echo.
echo Attend System startup complete!
echo Backend URL: http://localhost:5000
echo Frontend URL: http://localhost:3000
echo.
echo Press Ctrl+C in each terminal window to stop the servers
