@echo off
REM update-network-auto.bat - Script to update network configuration to auto-detect mode
REM Created June 4, 2025

echo ========================================================
echo    UPDATING NETWORK CONFIGURATION TO AUTO-DETECT MODE
echo ========================================================

set FRONTEND_PATH=%~dp0frontend

echo Generating new auto-detect network configuration file...

echo // Auto-generated by update-network-auto.bat > "%FRONTEND_PATH%\src\config\network.config.js"
echo // Last updated: %DATE% %TIME% >> "%FRONTEND_PATH%\src\config\network.config.js"
echo const defaultConfig = { >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   serverIP: "auto", >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   frontendPort: 3000, >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   backendPort: 5000, >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   qrServicePort: 5005, >> "%FRONTEND_PATH%\src\config\network.config.js"
echo   useHttps: false >> "%FRONTEND_PATH%\src\config\network.config.js"
echo }; >> "%FRONTEND_PATH%\src\config\network.config.js"
echo export default defaultConfig; >> "%FRONTEND_PATH%\src\config\network.config.js"

echo.
echo Network configuration updated to AUTO-DETECT mode!
echo.
echo This means the application will now:
echo 1. Automatically detect the best IP address to use based on your network
echo 2. Remember successfully connected IP addresses between sessions
echo 3. Work better when switching between different networks
echo.
echo To use the system now, run startall.bat or startall-network.bat as usual.
echo ========================================================

pause
